#Pull Jenkins Base Image
FROM ubuntu:latest

#Build the container
USER root
RUN adduser palosade
RUN usermod -a -G sudo palosade
RUN apt-get update -y
RUN apt-get install wget apt-transport-https gnupg lsb-release ruby-full -y

RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
RUN echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
RUN apt-get update -y
RUN apt-get install -y trivy
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

RUN wget -O /usr/bin/palosade-sbom.rb https://github.com/paragpatil2006/Exp1/blob/main/simple-sbom.rb
RUN apt-get clean

user palosade